root:
  path: "/"
  controller: BaseController::index
index_photos:
  path: "/photos"
  controller: photos\PhotosController::index
show_photos:
  path: "/photos/{id}"
  controller: photos\PhotosController::show